Uptime.Auction.Web/Models/BidModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Uptime.Auction.Web.Models
{
    public class BidModel
    {
        public int AuctionId { get; set; }
        public double BidPrice { get; set; }
    }
}

Uptime.Auction.Web/Models/LoginModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Uptime.Auction.Web.Models
{
    public class LoginModel
    {
        public string Username { get; set; }

        [DataType(DataType.Password)]
        public string Password { get; set; }

    }
}

Uptime.Auction.Web/Controllers/AuctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Uptime.Auction.Core;
using Uptime.Auction.Web.Models;

namespace Uptime.Auction.Web.Controllers
{
    [Route("[controller]")]
    [Route("")]
    [Authorize]
    public class AuctionController : Controller
    {
        private readonly AuctionService auctionService;

        public AuctionController(AuctionService auctionService)
        {
            this.auctionService = auctionService;
        }

        [Route("[action]")]
        [Route("")]
        public IActionResult Index()
        {
            var auctions = auctionService.ShowList();
            
            return View(auctions);
        }


        [HttpGet("[action]")]
        public IActionResult Details(int auctionId)
        {

            var auction = auctionService.ShowList().First(x => x.Id == auctionId && x.End > DateTime.Now);

            if (auction != null)
            {
                return View(auction);
            }
            else
            {
                throw new Exception("There's no auction with that ID");
            }
        }

        [HttpPost("[action]")]
        public IActionResult Bid([FromBody]BidModel bid)
        {
            auctionService.Bid(bid.AuctionId, bid.BidPrice);
            return Ok();
        }

        [HttpGet("[action]")]
        public IActionResult Create()
        {
            var auction = new Core.Auction();
            return View(auction);
        }

        [HttpPost("[action]")]
        public IActionResult Create(Core.Auction auction)
        {
            if (!ModelState.IsValid)
            {
                return View(auction);
            }
            else
            {
                auctionService.Create(auction.Item, auction.StartingPrice, auction.End);
                return RedirectToAction("Index");
            }
        }

        [HttpGet("[action]")]
        [AllowAnonymous]
        public IActionResult Login()
        {
            return View(new LoginModel());
        }

        [HttpPost("[action]")]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginModel login)
        {
            if (login.Username == "Teele" && login.Password == "jou")
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, login.Username),
                    new Claim(ClaimTypes.Role, "Administrator"),
                };

                var claimsIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties
                {
                    //AllowRefresh = <bool>,
                    // Refreshing the authentication session should be allowed.

                    //ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10),
                    // The time at which the authentication ticket expires. A 
                    // value set here overrides the ExpireTimeSpan option of 
                    // CookieAuthenticationOptions set with AddCookie.

                    //IsPersistent = true,
                    // Whether the authentication session is persisted across 
                    // multiple requests. Required when setting the 
                    // ExpireTimeSpan option of CookieAuthenticationOptions 
                    // set with AddCookie. Also required when setting 
                    // ExpiresUtc.

                    //IssuedUtc = <DateTimeOffset>,
                    // The time at which the authentication ticket was issued.

                    //RedirectUri = <string>
                    // The full path or absolute URI to be used as an http 
                    // redirect response value.
                };

                await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                authProperties);

                return RedirectToAction("Index");
            }
            else
            {
                return View(login);
            }


            

        }


    }
}

Uptime.Auction.Web/Views/Auction/Create.cshtml
@model Uptime.Auction.Core.Auction
@{
    Layout = "_Layout";
}

<div class="container">
    <div class="jumbotron">
        <h1>Create New Auction</h1>
    </div>
</div>
<div class="container">
    @using (Html.BeginForm("Create", "Auction", FormMethod.Post))
    {

    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Item)</dt>
        <dd>@Html.TextBoxFor(m => m.Item) @Html.ValidationMessageFor(model => model.Item)</dd>

        <dt>@Html.DisplayNameFor(model => model.StartingPrice)</dt>
        <dd>@Html.TextBoxFor(m => m.StartingPrice) @Html.ValidationMessageFor(model => model.StartingPrice)</dd>

        <dt>@Html.DisplayNameFor(model => model.End)</dt>
        <dd>@Html.TextBoxFor(m => m.End) @Html.ValidationMessageFor(model => model.End)</dd>
    </dl>

        <button type="submit" class="btn btn-secondary" id="submit">Submit</button>
    }
</div>

Uptime.Auction.Web/Views/Auction/Details.cshtml
@model Uptime.Auction.Core.Auction
@{
    var dateFormat = "yyyy-MM-dd";
    Layout = "_Layout";
}


<div class="container">
    <div class="jumbotron">
        <h1>Details</h1>
    </div>
</div>
<div class="container">
    <h4>@Model.Item</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>Starting Price</dt>
        <dd>@Model.StartingPrice</dd>

        <dt>Current Price</dt>
        <dd>@Model.CurrentPrice</dd>

        <dt>Started</dt>
        <dd>@Model.Start.ToString(dateFormat)</dd>

        <dt>Ends</dt>
        <dd>@Model.End.ToString(dateFormat)</dd>
    </dl>


    <div class="input-group" id="bid-input-group">
        <input type="text" class="form-control" id="bid-input" data-auction-id="@Model.Id">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button" id="bid-button">Bid</button>
        </div>
    </div>

    <button type="button" onclick="location.href='@Url.Action("Index")'" class="btn btn-secondary">Back to List</button>
</div>

Uptime.Auction.Web/Views/Auction/Index.cshtml
@model List<Uptime.Auction.Core.Auction>
@{
    Layout = "_Layout";
}

<div class="container">
    <div class="jumbotron">
        <h1>Auctions</h1>
    </div>
</div>
<div class="container">

    <table class="table" style="width:100%">
        <thead>
            <tr>
                <th>Item</th>
                <th>Starting Price</th>
                <th>Current Price</th>
                <th>Started</th>
                <th>Ends</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var auction in Model)
            {
                <tr>
                    <td>@auction.Item</td>
                    <td>@auction.StartingPrice $</td>
                    <td>@auction.CurrentPrice $</td>
                    <td>@auction.Start</td>
                    <td>@auction.End</td>
                    <td>@Html.ActionLink("Details", "Details", new { auctionId = auction.Id })</td>
                </tr>
            }
        </tbody>
    </table>
    <button type="button" onclick="location.href='@Url.Action("Create")'" class="btn btn-secondary">Create New Auction</button>
</div>
<div class="container">
    <input id="chat-input" />
    <button id="chat-button" class="btn btn-secondary btn-sm">Send</button>
    <div>
        <ul id="chat-message"></ul>
    </div>
</div>

<script>
    const connection = new signalR.HubConnectionBuilder()
        .withUrl("/chatHub")
        .build();

    connection.on("ReceiveMessage", (message) => {
        const msg = message.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
        const li = document.createElement("li");
        li.textContent = msg;
        document.getElementById("chat-message").appendChild(li);
    });

    connection.start().catch(err => console.error(err.toString()));

    document.getElementById("chat-button").addEventListener("click", event => {
        //const user = document.getElementById("userInput").value;
        const message = document.getElementById("chat-input").value;
        //, user, message
        connection.invoke("SendMessage", message).catch(err => console.error(err.toString()));
        event.preventDefault();
    });

</script>

Uptime.Auction.Web/Views/Auction/Login.cshtml
@model Uptime.Auction.Web.Models.LoginModel
@{
    Layout = "_Layout";
}

<div class="container">
    <div class="jumbotron">
        <h1>Login</h1>
    </div>
</div>
<div class="container">
    @using (Html.BeginForm("Login", "Auction", FormMethod.Post))
    {

        <dl class="dl-horizontal">
            <dt>@Html.DisplayNameFor(model => model.Username)</dt>
            <dd>@Html.TextBoxFor(m => m.Username) @Html.ValidationMessageFor(model => model.Username)</dd>

            <dt>@Html.DisplayNameFor(model => model.Password)</dt>
            <dd>@Html.TextBoxFor(m => m.Password) @Html.ValidationMessageFor(model => model.Password)</dd>

        </dl>

        <button type="submit" class="btn btn-secondary" id="submit">Submit</button>
    }
</div>

Uptime.Auction.Web/Views/Shared/_Layout.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Create new auction</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/js/bid.js"></script>
    <link href="~/css/page.css" rel="stylesheet" />

    <script src="~/js/signalr.js"></script>
</head>
<body>
    @RenderBody()
</body>
</html>